### ISSUE TITLE
Too many error files? memorized

### ISSUE THREAD

**Issue by adamramadhan** [codelucas/newspaper#117]
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/newspaper/parsers.py", line 65, in fromstring
    cls.doc = lxml.html.fromstring(html)
  File "/usr/local/lib/python3.4/site-packages/lxml/html/__init__.py", line 706, in fromstring
    doc = document_fromstring(html, parser=parser, base_url=base_url, **kw)
  File "/usr/local/lib/python3.4/site-packages/lxml/html/__init__.py", line 600, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src/lxml/lxml.etree.c:68121)
  File "parser.pxi", line 1786, in lxml.etree._parseMemoryDocument (src/lxml/lxml.etree.c:102470)
  File "parser.pxi", line 1667, in lxml.etree._parseDoc (src/lxml/lxml.etree.c:101229)
  File "parser.pxi", line 1035, in lxml.etree._BaseParser._parseUnicodeDoc (src/lxml/lxml.etree.c:96139)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:91290)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:92476)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:91904)
  File "<string>", line None
lxml.etree.XMLSyntaxError: line 777: b'ID logo already defined'
[Source parse ERR] http://liputan6.com
[Errno 24] Too many open files: '/root/.newspaper_scraper/memoized/liputan6.com.txt' <class 'OSError'> test.py 58

i got an error like this, basically its a simple crawler that crawl within a while: True, too many threads maybe?

**Comment by jwarzech** [comment]
I'm getting a lot of these errors as well:

```
[2015-03-12 00:02:41,640: WARNING/Worker-54] File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:91290)

2015-03-12 00:02:41,640 DEBG 'workers' stderr output:
[2015-03-12 00:02:41,640: WARNING/Worker-54] File "parser.pxi", line 683, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:92476)

2015-03-12 00:02:41,640 DEBG 'workers' stderr output:
[2015-03-12 00:02:41,640: WARNING/Worker-54] File "parser.pxi", line 631, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:91904)
```

**Comment by codelucas** [comment]
This critical memory leak should have been fixed in: https://github.com/codelucas/newspaper/issues/177
