### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1 in

### ISSUE THREAD

**Issue by desiregn** [codelucas/newspaper#155]
![screenshot-118](https://cloud.githubusercontent.com/assets/13287052/8992310/a20b2b76-371f-11e5-89a1-89bdce743e88.png)

Windows 8; Python 3.4

**Comment by SpicyMintCake** [comment]
Any chance anyone has found the solution to this? (Also afflicted by this problem)

**Comment by TwistingTwists** [comment]
➜  ~  pip install newspaper
Collecting newspaper
  Using cached newspaper-0.0.9.8.tar.gz
Collecting beautifulsoup4==4.3.2 (from newspaper)
  Using cached beautifulsoup4-4.3.2.tar.gz
Collecting Pillow==2.5.1 (from newspaper)
  Using cached Pillow-2.5.1.zip
Requirement already satisfied (use --upgrade to upgrade): PyYAML==3.11 in ./anaconda3/lib/python3.5/site-packages (from newspaper)
Collecting cssselect==0.9.1 (from newspaper)
  Using cached cssselect-0.9.1.tar.gz
Collecting lxml==3.3.5 (from newspaper)
  Using cached lxml-3.3.5.tar.gz
Collecting nltk==2.0.5 (from newspaper)
  Using cached nltk-2.0.5.tar.gz
    Complete output from command python setup.py egg_info:
    Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.21.tar.gz
    Extracting in /tmp/tmp7ixhh8fi
    Traceback (most recent call last):
      File "/tmp/pip-build-mf1prqjy/nltk/distribute_setup.py", line 143, in use_setuptools
        raise ImportError
    ImportError
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-mf1prqjy/nltk/setup.py", line 23, in <module>
        distribute_setup.use_setuptools()
      File "/tmp/pip-build-mf1prqjy/nltk/distribute_setup.py", line 145, in use_setuptools
        return _do_download(version, download_base, to_dir, download_delay)
      File "/tmp/pip-build-mf1prqjy/nltk/distribute_setup.py", line 125, in _do_download
        _build_egg(egg, tarball, to_dir)
      File "/tmp/pip-build-mf1prqjy/nltk/distribute_setup.py", line 99, in _build_egg
        _extractall(tar)
      File "/tmp/pip-build-mf1prqjy/nltk/distribute_setup.py", line 467, in _extractall
        self.chown(tarinfo, dirpath)
    TypeError: chown() missing 1 required positional argument: 'numeric_owner'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-mf1prqjy/nltk


I seem to have the same problem. Can't install `newspaper`.
@codelucas : Any help?

**Comment by halflings** [comment]
Got the same error as @TwistingTwists.

**Comment by yprez** [comment]
Is that Python 3 ?

**Comment by halflings** [comment]
Yes, installed it with Python 3:

    pip3 install newspaper
    Collecting newspaper
      Downloading newspaper-0.0.9.8.tar.gz (248kB)
        100% |████████████████████████████████| 249kB 2.1MB/s
    Collecting beautifulsoup4==4.3.2 (from newspaper)
      Downloading beautifulsoup4-4.3.2.tar.gz (143kB)
        100% |████████████████████████████████| 143kB 3.2MB/s
    Collecting Pillow==2.5.1 (from newspaper)
      Downloading Pillow-2.5.1.zip (6.9MB)
        100% |████████████████████████████████| 6.9MB 86kB/s
    Collecting PyYAML==3.11 (from newspaper)
      Downloading PyYAML-3.11.tar.gz (248kB)
        100% |████████████████████████████████| 249kB 2.1MB/s
    Collecting cssselect==0.9.1 (from newspaper)
      Downloading cssselect-0.9.1.tar.gz
    Collecting lxml==3.3.5 (from newspaper)
      Downloading lxml-3.3.5.tar.gz (3.5MB)
        100% |████████████████████████████████| 3.5MB 169kB/s
    Collecting nltk==2.0.5 (from newspaper)
      Downloading nltk-2.0.5.tar.gz (954kB)
        100% |████████████████████████████████| 958kB 622kB/s
        Complete output from command python setup.py egg_info:
        Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.21.tar.gz
        Extracting in /var/folders/jy/r8str2rn2qlgl8gg1xcplr380000gn/T/tmpcklo15nj
        Traceback (most recent call last):
          File "/private/var/folders/jy/r8str2rn2qlgl8gg1xcplr380000gn/T/pip-build-lbxdl7uv/nltk/distribute_setup.py", line 143, in use_setuptools
            raise ImportError
        ImportError

        During handling of the above exception, another exception occurred:

        Traceback (most recent call last):
          File "<string>", line 20, in <module>
          File "/private/var/folders/jy/r8str2rn2qlgl8gg1xcplr380000gn/T/pip-build-lbxdl7uv/nltk/setup.py", line 23, in <module>
            distribute_setup.use_setuptools()
          File "/private/var/folders/jy/r8str2rn2qlgl8gg1xcplr380000gn/T/pip-build-lbxdl7uv/nltk/distribute_setup.py", line 145, in use_setuptools
            return _do_download(version, download_base, to_dir, download_delay)
          File "/private/var/folders/jy/r8str2rn2qlgl8gg1xcplr380000gn/T/pip-build-lbxdl7uv/nltk/distribute_setup.py", line 125, in _do_download
            _build_egg(egg, tarball, to_dir)
          File "/private/var/folders/jy/r8str2rn2qlgl8gg1xcplr380000gn/T/pip-build-lbxdl7uv/nltk/distribute_setup.py", line 99, in _build_egg
            _extractall(tar)
          File "/private/var/folders/jy/r8str2rn2qlgl8gg1xcplr380000gn/T/pip-build-lbxdl7uv/nltk/distribute_setup.py", line 467, in _extractall
            self.chown(tarinfo, dirpath)
        TypeError: chown() missing 1 required positional argument: 'numeric_owner'

        ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/jy/r8str2rn2qlgl8gg1xcplr380000gn/T/pip-build-lbxdl7uv/nltk

But it seems this might be related to NLTK.

**Comment by yprez** [comment]
I think that on pypi "newspaper" is the python2 branch. Try: `pip install newspaper3k`

**Comment by halflings** [comment]
Oh, right! Thanks :) Didn't notice the change to newspaper3k (last time I used it things were still a bit confusing).

The other poster seems to be using `pip` though, so probably Python 2.7

**Comment by vsanghvi007** [comment]
hey i am having the same error when i am using python 2.7 distribution of anaconda.

117-60-41-155-wireless1x:anaconda vsanghvi007$ **/Users/vsanghvi007/anaconda/bin/pip install newspaper**
Collecting newspaper
  Using cached newspaper-0.0.9.8.tar.gz
Collecting beautifulsoup4==4.3.2 (from newspaper)
  Using cached beautifulsoup4-4.3.2.tar.gz
Collecting Pillow==2.5.1 (from newspaper)
  Using cached Pillow-2.5.1-cp27-none-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.whl
Requirement already satisfied (use --upgrade to upgrade): PyYAML==3.11 in ./lib/python2.7/site-packages (from newspaper)
Collecting cssselect==0.9.1 (from newspaper)
  Using cached cssselect-0.9.1.tar.gz
Collecting lxml==3.3.5 (from newspaper)
  Using cached lxml-3.3.5.tar.gz
Collecting nltk==2.0.5 (from newspaper)
  Using cached nltk-2.0.5.tar.gz
    Complete output from command python setup.py egg_info:
    Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.21.tar.gz
    Extracting in /var/folders/m6/jkhz4t6x7jn2rf40btzg7y5c0000gn/T/tmp7B3Hrz
    Now working in /var/folders/m6/jkhz4t6x7jn2rf40btzg7y5c0000gn/T/tmp7B3Hrz/distribute-0.6.21
    Building a Distribute egg in /private/var/folders/m6/jkhz4t6x7jn2rf40btzg7y5c0000gn/T/pip-build-QoC1nV/nltk
    Traceback (most recent call last):
      File "setup.py", line 37, in <module>
        exec(open(init_path).read(), d)
      File "<string>", line 8, in <module>
      File "/private/var/folders/m6/jkhz4t6x7jn2rf40btzg7y5c0000gn/T/tmp7B3Hrz/distribute-0.6.21/setuptools/__init__.py", line 2, in <module>
        from setuptools.extension import Extension, Library
      File "/private/var/folders/m6/jkhz4t6x7jn2rf40btzg7y5c0000gn/T/tmp7B3Hrz/distribute-0.6.21/setuptools/extension.py", line 2, in <module>
        from setuptools.dist import _get_unpatched
      File "/private/var/folders/m6/jkhz4t6x7jn2rf40btzg7y5c0000gn/T/tmp7B3Hrz/distribute-0.6.21/setuptools/dist.py", line 6, in <module>
        from setuptools.command.install import install
      File "/private/var/folders/m6/jkhz4t6x7jn2rf40btzg7y5c0000gn/T/tmp7B3Hrz/distribute-0.6.21/setuptools/command/__init__.py", line 8, in <module>
        from setuptools.command import install_scripts
      File "/private/var/folders/m6/jkhz4t6x7jn2rf40btzg7y5c0000gn/T/tmp7B3Hrz/distribute-0.6.21/setuptools/command/install_scripts.py", line 3, in <module>
        from pkg_resources import Distribution, PathMetadata, ensure_directory
      File "/private/var/folders/m6/jkhz4t6x7jn2rf40btzg7y5c0000gn/T/tmp7B3Hrz/distribute-0.6.21/pkg_resources.py", line 2729, in <module>
        add_activation_listener(lambda dist: dist.activate())
      File "/private/var/folders/m6/jkhz4t6x7jn2rf40btzg7y5c0000gn/T/tmp7B3Hrz/distribute-0.6.21/pkg_resources.py", line 700, in subscribe
        callback(dist)
      File "/private/var/folders/m6/jkhz4t6x7jn2rf40btzg7y5c0000gn/T/tmp7B3Hrz/distribute-0.6.21/pkg_resources.py", line 2729, in <lambda>
        add_activation_listener(lambda dist: dist.activate())
      File "/private/var/folders/m6/jkhz4t6x7jn2rf40btzg7y5c0000gn/T/tmp7B3Hrz/distribute-0.6.21/pkg_resources.py", line 2229, in activate
        self.insert_on(path)
      File "/private/var/folders/m6/jkhz4t6x7jn2rf40btzg7y5c0000gn/T/tmp7B3Hrz/distribute-0.6.21/pkg_resources.py", line 2330, in insert_on
        "with distribute. Found one at %s" % str(self.location))
    ValueError: A 0.7-series setuptools cannot be installed with distribute. Found one at /Users/vsanghvi007/anaconda/lib/python2.7/site-packages/setuptools-20.7.0-py2.7.egg
    /private/var/folders/m6/jkhz4t6x7jn2rf40btzg7y5c0000gn/T/pip-build-QoC1nV/nltk/distribute-0.6.21-py2.7.egg
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/m6/jkhz4t6x7jn2rf40btzg7y5c0000gn/T/pip-build-QoC1nV/nltk/setup.py", line 23, in <module>
        distribute_setup.use_setuptools()
      File "/private/var/folders/m6/jkhz4t6x7jn2rf40btzg7y5c0000gn/T/pip-build-QoC1nV/nltk/distribute_setup.py", line 145, in use_setuptools
        return _do_download(version, download_base, to_dir, download_delay)
      File "/private/var/folders/m6/jkhz4t6x7jn2rf40btzg7y5c0000gn/T/pip-build-QoC1nV/nltk/distribute_setup.py", line 125, in _do_download
        _build_egg(egg, tarball, to_dir)
      File "/private/var/folders/m6/jkhz4t6x7jn2rf40btzg7y5c0000gn/T/pip-build-QoC1nV/nltk/distribute_setup.py", line 116, in _build_egg
        raise IOError('Could not build the egg.')
    IOError: Could not build the egg.
    
    ----------------------------------------
**Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/m6/jkhz4t6x7jn2rf40btzg7y5c0000gn/T/pip-build-QoC1nV/nltk/**

**Comment by vsanghvi007** [comment]
Can you tell me what worked for you ? i dont want to upgrade to python 3 anaconda as  everything else need 2.7 distribution of anaconda

**Comment by vsanghvi007** [comment]
@yprez @halflings @TwistingTwists

**Comment by vinayakd20** [comment]
Hi , I am also gettting the same problem with installing nltk 2.0.1 but nltk 3 gets installed nicely. And I need nltk 2.0.1. I am using Anaconda 2 package witht python 2.7.11 .. Can anyone pls help? ..

Thanks

**Comment by yprez** [comment]
@vsanghvi007 @vinayakd20 what happens when you do `pip install nltk==2.0.5`?

**Comment by yprez** [comment]
Closing for now. Feel free to reopen if you still haven't found a solution.

**Comment by jetilton** [comment]
I am having the same issue.  I have tried the following fixes:
[Upgrade setup tools](http://stackoverflow.com/questions/31719816/pip-fails-to-install-anything-error-invalid-command-egg-info)
[This one](http://stackoverflow.com/questions/35469917/python-package-newspaper-install-error)
[Download from Git](http://stackoverflow.com/questions/30650098/error-in-installing-newspaper3k-package-via-pip)  But this downloaded newspaper3k, I am running Python 2.7
[Download from source](https://groups.google.com/forum/#!topic/nltk-users/5hojEAby6Vo)
I understand it is a problem with nltk, but I cannot find a solution and am wondering if anyone else has.
Pip is up to date, I am running python 2.7 on Mac OSX and have tried the correct newspaper version, (as well as incorrect when downloading from git)

Thanks

**Comment by adrienthiery** [comment]
I don't know if that could be of any use, but I had the same problem on Ubuntu 16.04.

The thing is that `apt-get` has only version 20.0.7 of setup-tools, and pip 8.8.1, that can't update setup-tools to a newer version. 

I found the solution here : http://askubuntu.com/questions/683601/how-to-upgrade-python-setuptools-12-2-on-ubuntu-15-04

**Comment by deepakmishra** [comment]
Same problem
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-y173g0/MySQL-python/

**Comment by codelucas** [comment]
Hey all, I am reopening this issue. Even though @yprez pointed out correctly that you should be downloading newspaper3k or newspaper (via pip3 or pip) depending on your python version. This detail is tough for a lot of people to follow (including myself!) given how many comments are on this issue and how many complaints there have been.

I'm working on a Pull Request in the setup.py file to fire print warnings to the user if he/she is attempting to install on a wrong version! Will be doing something to this stackoverflow post: https://stackoverflow.com/questions/19534896/enforcing-python-version-in-setup-py

**Comment by codelucas** [comment]
Check out this PR guys, it should make the installation process on python2 and python3 much easier: https://github.com/codelucas/newspaper/commit/422a9f48ea01268cc266ca9f33174ecd45753e7b

**Comment by codelucas** [comment]
Also pushed a similar warning + guard for newspaper3k's setup.py file here!
https://github.com/codelucas/newspaper/commit/fba5017691104d9612ca80809d361e23e8fbadf8

**Comment by codelucas** [comment]
Doesn't this error look better guys?
```
~VIRTUAL_ENV » pip install newspaper                                                                                                                       lucasou-yang@C02SQDX8G8WN
Collecting newspaper
  Downloading newspaper-0.0.9.9.tar.gz (49kB)
    100% |████████████████████████████████| 51kB 1.7MB/s
    Complete output from command python setup.py egg_info:
    WARNING! You are attempting to install newspaper's python2 repository on python3. PLEASE RUN `$ pip3 install newspaper3k` for python3 or `$ pip install newspaper` for python2

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/x2/rtth0p7j3nqgt9wfqtk9m23r0000gq/T/pip-build-9172lu7n/newspaper/
```

;) 💯

**Comment by yprez** [comment]
@codelucas looks great!

But I noticed that the message doesn't show for me when running `pip install newspaper` on Python 3, but when running `setup.py` in the repo it works as expected. Maybe the version on pypi is not up to date?

**Comment by codelucas** [comment]
@yprez good catch! Oops I should have pushed it as a new version - doing so now

**Comment by codelucas** [comment]
@yprez fixed! Just pushed the latest python-2-branch to pypi. Try installing `newspaper` on python3/pip3 now

```
~VIRTUAL_ENV » pip install newspaper                                                                                                                        l@mbp
Collecting newspaper
  Using cached newspaper-0.1.0.7.tar.gz
    Complete output from command python setup.py egg_info:
    WARNING! You are attempting to install newspaper's python2 repository on python3. PLEASE RUN `$ pip3 install newspaper3k` for python3 or `$ pip install newspaper` for python2
```

**Comment by yprez** [comment]
@codelucas works now!

**Comment by HodorTheCoder** [comment]
I wanted to leave an update that fixed a very similar issue for me on Ubuntu 16.04.  I was having nltk crap out because it couldn't install distribute properly:

`Collecting nltk==2.0.5 (from newspaper)
  Downloading nltk-2.0.5.tar.gz (954kB)
    100% |████████████████████████████████| 962kB 1.2MB/s 
    Complete output from command python setup.py egg_info:
    Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.21.tar.gz
    Extracting in /tmp/tmpiKrE4K
    Now working in /tmp/tmpiKrE4K/distribute-0.6.21
    Building a Distribute egg in /tmp/pip-build-JADRCf/nltk
    Traceback (most recent call last):
      File "setup.py", line 37, in <module>
        exec(open(init_path).read(), d)
      File "<string>", line 8, in <module>
      File "/tmp/tmpiKrE4K/distribute-0.6.21/setuptools/__init__.py", line 2, in <module>
        from setuptools.extension import Extension, Library
      File "/tmp/tmpiKrE4K/distribute-0.6.21/setuptools/extension.py", line 2, in <module>
        from setuptools.dist import _get_unpatched
      File "/tmp/tmpiKrE4K/distribute-0.6.21/setuptools/dist.py", line 6, in <module>
        from setuptools.command.install import install
      File "/tmp/tmpiKrE4K/distribute-0.6.21/setuptools/command/__init__.py", line 8, in <module>
        from setuptools.command import install_scripts
      File "/tmp/tmpiKrE4K/distribute-0.6.21/setuptools/command/install_scripts.py", line 3, in <module>
        from pkg_resources import Distribution, PathMetadata, ensure_directory
      File "/tmp/tmpiKrE4K/distribute-0.6.21/pkg_resources.py", line 2729, in <module>
        add_activation_listener(lambda dist: dist.activate())
      File "/tmp/tmpiKrE4K/distribute-0.6.21/pkg_resources.py", line 700, in subscribe
        callback(dist)
      File "/tmp/tmpiKrE4K/distribute-0.6.21/pkg_resources.py", line 2729, in <lambda>
        add_activation_listener(lambda dist: dist.activate())
      File "/tmp/tmpiKrE4K/distribute-0.6.21/pkg_resources.py", line 2229, in activate
        self.insert_on(path)
      File "/tmp/tmpiKrE4K/distribute-0.6.21/pkg_resources.py", line 2330, in insert_on
        "with distribute. Found one at %s" % str(self.location))
    ValueError: A 0.7-series setuptools cannot be installed with distribute. Found one at /usr/lib/python2.7/dist-packages
    /tmp/pip-build-JADRCf/nltk/distribute-0.6.21-py2.7.egg
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-JADRCf/nltk/setup.py", line 23, in <module>
        distribute_setup.use_setuptools()
      File "distribute_setup.py", line 145, in use_setuptools
        return _do_download(version, download_base, to_dir, download_delay)
      File "distribute_setup.py", line 125, in _do_download
        _build_egg(egg, tarball, to_dir)
      File "distribute_setup.py", line 116, in _build_egg
        raise IOError('Could not build the egg.')
    IOError: Could not build the egg.
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-JADRCf/nltk/
`

Even trying to do an independent

`sudo -H pip install distribute`

was throwing an error about missing a _marklib module, so after trying a few thing I found a stackexchange post that suggested installing distribute using easy_install:

`sudo -H easy_install distribute`

Once I did this, distribute installed properly and then I was able to complete my newspaper install using pip.

**Comment by siddharthvdn** [comment]
This solved the issue for me.
` 
apt remove python-setuptools 
pip install newspaper 
`

**Comment by caiyajing9210** [comment]
```
Collecting nltk==2.0.5 (from newspaper)
  Using cached nltk-2.0.5.tar.gz
    Complete output from command python setup.py egg_info:
    Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.21.tar.gz
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-7KVnCt/nltk/setup.py", line 23, in <module>
        distribute_setup.use_setuptools()
      File "distribute_setup.py", line 145, in use_setuptools
        return _do_download(version, download_base, to_dir, download_delay)
      File "distribute_setup.py", line 124, in _do_download
        to_dir, download_delay)
      File "distribute_setup.py", line 193, in download_setuptools
        src = urlopen(url)
      File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
        return opener.open(url, data, timeout)
      File "/usr/lib/python2.7/urllib2.py", line 435, in open
        response = meth(req, response)
      File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
        'http', request, response, code, msg, hdrs)
      File "/usr/lib/python2.7/urllib2.py", line 473, in error
        return self._call_chain(*args)
      File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
        result = func(*args)
      File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
        raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
    urllib2.HTTPError: HTTP Error 403: SSL is required
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-7KVnCt/nltk/

```
I tried to install newspaper on Ubuntu 16.04. the python version is 2.7.12
Can any tell me how to fix the problem?

**Comment by johnkjoseph** [comment]
@caiyajing9210 Did you get it to work?

**Comment by JJGG8899** [comment]
I am having exactly the same issue as caiyajing9210.  urllib2.HTTPError: HTTP Error 403: SSL is required. Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-7KVnCt/nltk/    Any idea how to get rid of this??

**Comment by JJGG8899** [comment]
@caiyajing9210 
Just made it work.  Problem is Collecting nltk==2.0.5 (from newspaper), nltk version is too low.
Solution:
1.Go to newspaper python2 branch https://github.com/codelucas/newspaper/tree/python-2-head/newspaper, download this repo and install this package locally.
2.After you download it, in its requirements.txt, change nltk==2.0.5 to nltk==3.0.1
3.run pip install -r requirements.txt and python setup.py install to build it locally.
