### ISSUE TITLE
HTMLParseError

### ISSUE THREAD

**Issue by TheShapGuy** [codelucas/newspaper#165]
Getting this error while running Python3 with newspaper in VirtualEnv. However if I run this in Python2 Virtualenv it works seamlessly. 

Running OS X 10.10

The Script

```python
import newspaper
paper = newspaper.build('http://androidweekly.net/issues/issue-171', memoize_articles=False)


for i in paper.articles:
    print(i)

```
The exception
```python
Traceback (most recent call last):
  File "rx.py", line 1, in <module>
    import newspaper
  File "/Users/shapathneupane/Desktop/saito/lib/python3.5/site-packages/newspaper/__init__.py", line 10, in <module>
    from .article import Article, ArticleException
  File "/Users/shapathneupane/Desktop/saito/lib/python3.5/site-packages/newspaper/article.py", line 13, in <module>
    from . import network
  File "/Users/shapathneupane/Desktop/saito/lib/python3.5/site-packages/newspaper/network.py", line 14, in <module>
    from .configuration import Configuration
  File "/Users/shapathneupane/Desktop/saito/lib/python3.5/site-packages/newspaper/configuration.py", line 15, in <module>
    from .parsers import Parser
  File "/Users/shapathneupane/Desktop/saito/lib/python3.5/site-packages/newspaper/parsers.py", line 16, in <module>
    from bs4 import UnicodeDammit
  File "/Users/shapathneupane/Desktop/saito/lib/python3.5/site-packages/bs4/__init__.py", line 30, in <module>
    from .builder import builder_registry, ParserRejectedMarkup
  File "/Users/shapathneupane/Desktop/saito/lib/python3.5/site-packages/bs4/builder/__init__.py", line 308, in <module>
    from . import _htmlparser
  File "/Users/shapathneupane/Desktop/saito/lib/python3.5/site-packages/bs4/builder/_htmlparser.py", line 7, in <module>
    from html.parser import (
ImportError: cannot import name 'HTMLParseError'
```

**Comment by muranava** [comment]
i followed this and updated beautiful soup http://stackoverflow.com/questions/28745153/importing-bs4-in-python-3-5

**Comment by AlJohri** [comment]
yup, as @muranava said, just upgrade bs4
here's a PR: https://github.com/codelucas/newspaper/pull/171

**Comment by codelucas** [comment]
Thanks for the fix guys! It's been merged and should reflect in pip soon
