### ISSUE TITLE
Improve test assertions

### ISSUE THREAD

**Issue by yprez** [codelucas/newspaper#200]
Currently, when the some assertion in the tests are failing, the reason isn't shown and it requires further debugging.

For example:

```
Traceback (most recent call last):
  File "tests/unit_tests.py", line 136, in runTest
    self.test_nlp_body()
  File "tests/unit_tests.py", line 43, in run
    method(*args, **kw)
  File "tests/unit_tests.py", line 262, in test_nlp_body
    assert self.article.summary == SUMMARY

AssertionError
```

This is because the `assert` statement is used with the regular `unittest`, instead of of `assertEquals`, `assertTrue` or other unittest methods.

I see two solutions to this.

1. Use py.test with the current tests.
2. Switch to using unittest assertEquals statements (ugly and outdated imo).

The main feature of py.test is dealing with assert statements as test assertions. If failing, it'll show the exact drilldown of why the assertions failed, down to the single missing character (for example).

It shouldn't be too hard to switch to py.test from the current test runner, and I think it'll improve the test suite a lot, and will make it easier to write new tests when needed. I noticed that tests are often skipped for new features, maybe this can help...

**Comment by yprez** [comment]
@codelucas I still would prefer py.test, but if you're happy with the changes in #203 this can be closed.

**Comment by yprez** [comment]
After #203 `ExhaustiveFullTextCase` is executed every time.
Maybe it should be split into another file, and executed from there when needed.
