### ISSUE TITLE
Parsing issue - BadStatus line when parsing articles

### ISSUE THREAD

**Issue by yprez** [codelucas/newspaper#210]
Looks like it's caused by some images returning an invalid http status code...

The code:
```
import newspaper
article = newspaper.Article(url='http://www.himalayanwindowsinc.com/itineraries/show/253')
article.download()
article.parse()
```

The error:
```
Traceback (most recent call last):
  File "/home/yuri/virtualenvs/newspaper/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 3066, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-6-df704f976c28>", line 1, in <module>
    article.parse()
  File "/home/yuri/repos/newspaper/newspaper/article.py", line 228, in parse
    self.fetch_images()
  File "/home/yuri/repos/newspaper/newspaper/article.py", line 247, in fetch_images
    self.set_top_img(first_img)
  File "/home/yuri/repos/newspaper/newspaper/article.py", line 415, in set_top_img
    if s.satisfies_requirements(src_url):
  File "/home/yuri/repos/newspaper/newspaper/images.py", line 227, in satisfies_requirements
    img_url, self.useragent, referer=self.url)
  File "/home/yuri/repos/newspaper/newspaper/images.py", line 170, in fetch_image_dimension
    return fetch_url(url, useragent, referer, retries, dimension=True)
  File "/home/yuri/repos/newspaper/newspaper/images.py", line 102, in fetch_url
    open_req = opener.open(req, timeout=5)
  File "/usr/lib/python3.5/urllib/request.py", line 465, in open
    response = self._open(req, data)
  File "/usr/lib/python3.5/urllib/request.py", line 483, in _open
    '_open', req)
  File "/usr/lib/python3.5/urllib/request.py", line 443, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 1268, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.5/urllib/request.py", line 1243, in do_open
    r = h.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1174, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 282, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 264, in _read_status
    raise BadStatusLine(line)
http.client.BadStatusLine: 
```

**Comment by yprez** [comment]
This is caused by bad image urls, e.g. `http://www.himalayanwindowsinc.com/uploads/\r\nimages/Shangri-La-Tibet-Lhasa.jpg`, but still not a reason to fail with an exception. The images should be excluded instead...
