### ISSUE TITLE
Parsing issue - UnicodeEncodeError in get_parsing_candidate()

### ISSUE THREAD

**Issue by yprez** [codelucas/newspaper#211]
```
import newspaper
article = newspaper.Article(url='http://waynemessick.com/marketing/small-business-internet-marketing-advertising-strategies')
article.download()
article.parse()
```

Causes:
```
Traceback (most recent call last):
  File "/home/yuri/repos/newspaper/newspaper/article.py", line 166, in parse
    parse_candidate = self.get_parse_candidate()
  File "/home/yuri/repos/newspaper/newspaper/article.py", line 333, in get_parse_candidate
    return RawHelper.get_parsing_candidate(self.url, self.html)
  File "/home/yuri/repos/newspaper/newspaper/utils.py", line 59, in get_parsing_candidate
    raw_html = raw_html.encode('utf-8')
UnicodeEncodeError: 'utf-8' codec can't encode character '\ude7e' in position 13277: surrogates not allowed
```

**Comment by yprez** [comment]
Also encountered on:

http://tayloringit.com/2016/03/ltmooc16-level-2-a-facilitators-reflection-on-artificial-intelligence-ai/
http://newmoonmanifesting.com/thirst-for-innovation-aquarius-new-moon/
