### ISSUE TITLE
Import Error on El Capitain

### ISSUE THREAD

**Issue by bwghughes** [codelucas/newspaper#220]
I have a pyenv virtualenv running 2.7.11. I run the following:

``` pip install newspaper ```

Which runs fine.

When I run the REPL I get the following:

```
Python 2.7.11 (default, Feb 22 2016, 10:04:27)
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import newspaper
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ben/.pyenv/versions/burtonmail/lib/python2.7/site-packages/newspaper/__init__.py", line 10, in <module>
    from .article import Article, ArticleException
  File "/Users/ben/.pyenv/versions/burtonmail/lib/python2.7/site-packages/newspaper/article.py", line 12, in <module>
    from . import images
  File "/Users/ben/.pyenv/versions/burtonmail/lib/python2.7/site-packages/newspaper/images.py", line 19, in <module>
    from PIL import Image, ImageFile
  File "/Users/ben/.pyenv/versions/burtonmail/lib/python2.7/site-packages/PIL/Image.py", line 66, in <module>
    from PIL import _imaging as core
ImportError: dlopen(/Users/ben/.pyenv/versions/burtonmail/lib/python2.7/site-packages/PIL/_imaging.so, 2): Symbol not found: _PyUnicodeUCS2_AsLatin1String
  Referenced from: /Users/ben/.pyenv/versions/burtonmail/lib/python2.7/site-packages/PIL/_imaging.so
  Expected in: flat namespace
 in /Users/ben/.pyenv/versions/burtonmail/lib/python2.7/site-packages/PIL/_imaging.so
>>>
```

It looks to be a problem with linking PIL references but I'm not sure how to proceed.

**Comment by yprez** [comment]
Can you try upgrading Pillow (`pip install -U Pillow`) and see what happens?

**Comment by bwghughes** [comment]
Hey - sure I did that - however the problem still persists.

**Comment by yprez** [comment]
Weird...
In any case, it's some issue with Pillow, so I think you'll have better luck opening an issue there: https://github.com/python-pillow/Pillow

**Comment by bwghughes** [comment]
OK - thanks !!
