### ISSUE TITLE
Cant get text from page

### ISSUE THREAD

**Issue by xxxbobrxxx** [codelucas/newspaper#286]
URL: http://khabtime.info/news/show/?id_blog=35467

I can add mo urls if needed

**Comment by khardsonhurley** [comment]
I cannot get text from urls either. I keep getting this error:
>>> import newspaper
>>> articleobj=newspaper.Article('http://elcomidista.elpais.com/elcomidista/2016/07/27/receta/1469653710_388939.html')
>>> articleobj
<newspaper.article.Article object at 0x7fc577c37490>
>>> articleobj.url
u'http://elcomidista.elpais.com/elcomidista/2016/07/27/receta/1469653710_388939.html'
>>> articleobj.text
u''
>>> articleobj.download()
>>> articleobj.parse()
Traceback (most recent call last):
  File "/home/vagrant/src/Project/env/local/lib/python2.7/site-packages/newspaper/parsers.py", line 54, in fromstring
    cls.doc = lxml.html.fromstring(html)
  File "/home/vagrant/src/Project/env/local/lib/python2.7/site-packages/lxml/html/__init__.py", line 706, in fromstring
    doc = document_fromstring(html, parser=parser, base_url=base_url, **kw)
  File "/home/vagrant/src/Project/env/local/lib/python2.7/site-packages/lxml/html/__init__.py", line 600, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src/lxml/lxml.etree.c:68121)
  File "parser.pxi", line 1786, in lxml.etree._parseMemoryDocument (src/lxml/lxml.etree.c:102470)
  File "parser.pxi", line 1667, in lxml.etree._parseDoc (src/lxml/lxml.etree.c:101229)
  File "parser.pxi", line 1035, in lxml.etree._BaseParser._parseUnicodeDoc (src/lxml/lxml.etree.c:96139)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:91290)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:92476)
  File "parser.pxi", line 633, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:91939)
XMLSyntaxError: None

**Comment by thundergolfer** [comment]
Is this bug fixed? I tried the article provided by @khardsonhurley and it worked fine. @yprez ?
