### ISSUE TITLE
extract content from a html file

### ISSUE THREAD

**Issue by crosofg** [codelucas/newspaper#291]
How to extract content from html file generated by headless browsers like pyqt

**Comment by yprez** [comment]
Try `set_html()`, Something like:

```
article = newspaper.Article()
article.set_html(html)

article.parse()
article.nlp()
```

**Comment by crosofg** [comment]
Now I am getting other error
```
Traceback (most recent call last):
  File "/home/ubuntu/workspace/newspaperrepo/newspaperExample.py", line 1, in <module>
    from newspaper import Article
  File "/usr/local/lib/python2.7/dist-packages/newspaper3k-0.1.8-py2.7.egg/newspaper/__init__.py", line 10, in <module>
    from .article import Article, ArticleException
  File "/usr/local/lib/python2.7/dist-packages/newspaper3k-0.1.8-py2.7.egg/newspaper/article.py", line 12, in <module>
    from . import images
  File "/usr/local/lib/python2.7/dist-packages/newspaper3k-0.1.8-py2.7.egg/newspaper/images.py", line 15, in <module>
    import urllib.parse
ImportError: No module named parse
```

**Comment by yprez** [comment]
Try `Article(url='')` or `Article(url='http://example.com/test-url')`

**Comment by yprez** [comment]
@crosofg this should do it, feel free to reopen if it still doesn't work.

**Comment by km5ar** [comment]
this method above doesn't seems to be working anymore, any thoughts? 

article = newspaper.Article(url = "")
article.set_html(html)
article.parse()
article.text
