### ISSUE TITLE
no Module named parse

### ISSUE THREAD

**Issue by crosofg** [codelucas/newspaper#292]
```
Traceback (most recent call last):
  File "newspaperExample.py", line 1, in <module>
    from newspaper import Article
  File "/usr/local/lib/python2.7/dist-packages/newspaper3k-0.1.8-py2.7.egg/newspaper/__init__.py", line 10, in <module>
    from .article import Article, ArticleException
  File "/usr/local/lib/python2.7/dist-packages/newspaper3k-0.1.8-py2.7.egg/newspaper/article.py", line 12, in <module>
    from . import images
  File "/usr/local/lib/python2.7/dist-packages/newspaper3k-0.1.8-py2.7.egg/newspaper/images.py", line 15, in <module>
    import urllib.parse
ImportError: No module named parse
```
What could be the issue?

**Comment by crosofg** [comment]
now using python3
