### ISSUE TITLE
Error on importing newspaper

### ISSUE THREAD

**Issue by MohiuddinM** [codelucas/newspaper#316]
```
Python 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 07:18:10) [MSC v.1900 32 bit (Intel)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> import newspaper
Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    import newspaper
  File "C:\Python36\lib\site-packages\newspaper\__init__.py", line 10, in <module>
    from .article import Article, ArticleException
  File "C:\Python36\lib\site-packages\newspaper\article.py", line 13, in <module>
    from . import network
  File "C:\Python36\lib\site-packages\newspaper\network.py", line 14, in <module>
    from .configuration import Configuration
  File "C:\Python36\lib\site-packages\newspaper\configuration.py", line 15, in <module>
    from .parsers import Parser
  File "C:\Python36\lib\site-packages\newspaper\parsers.py", line 19, in <module>
    from . import text
  File "C:\Python36\lib\site-packages\newspaper\text.py", line 59, in <module>
    class StopWords(object):
  File "C:\Python36\lib\site-packages\newspaper\text.py", line 62, in StopWords
    "[^\\p{Ll}\\p{Lu}\\p{Lt}\\p{Lo}\\p{Nd}\\p{Pc}\\s]")
  File "C:\Python36\lib\re.py", line 233, in compile
    return _compile(pattern, flags)
  File "C:\Python36\lib\re.py", line 301, in _compile
    p = sre_compile.compile(pattern, flags)
  File "C:\Python36\lib\sre_compile.py", line 562, in compile
    p = sre_parse.parse(p, flags)
  File "C:\Python36\lib\sre_parse.py", line 856, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, False)
  File "C:\Python36\lib\sre_parse.py", line 415, in _parse_sub
    itemsappend(_parse(source, state, verbose))
  File "C:\Python36\lib\sre_parse.py", line 526, in _parse
    code1 = _class_escape(source, this)
  File "C:\Python36\lib\sre_parse.py", line 336, in _class_escape
    raise source.error('bad escape %s' % escape, len(escape))
sre_constants.error: bad escape \p at position 2

```

**Comment by codelucas** [comment]
Just pushed a new binary to pip/pypi via https://pypi.python.org/pypi?%3Aaction=pkg_edit&name=newspaper3k. The new binary contains the bugfix here:

https://github.com/codelucas/newspaper/pull/315
