### ISSUE TITLE
Can't download news from certain URLs

### ISSUE THREAD

**Issue by mcgradyjason** [codelucas/newspaper#318]
**First case: Tag text invalid**

```
a = Article('https://investor.lilly.com/releasedetail.cfm?ReleaseID=1006564')
a.download()
a.parse()
```

>  a = Article('https://investor.lilly.com/releasedetail.cfm?ReleaseID=1006564')
> a.download()
> a.parse()
> Traceback (most recent call last):
>   File "C:\Users\jzhang2\AppData\Local\Continuum\Anaconda2\lib\site-packages\newspaper\parsers.py", line 54, in fromstring
>     cls.doc = lxml.html.fromstring(html)
>   File "C:\Users\jzhang2\AppData\Local\Continuum\Anaconda2\lib\site-packages\lxml\html\__init__.py", line 706, in fromstring
>     doc = document_fromstring(html, parser=parser, base_url=base_url, **kw)
>   File "C:\Users\jzhang2\AppData\Local\Continuum\Anaconda2\lib\site-packages\lxml\html\__init__.py", line 600, in document_fromstring
>     value = etree.fromstring(html, parser, **kw)
>   File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src\lxml\lxml.etree.c:68121)
>   File "parser.pxi", line 1786, in lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:102470)
>   File "parser.pxi", line 1667, in lxml.etree._parseDoc (src\lxml\lxml.etree.c:101229)
>   File "parser.pxi", line 1035, in lxml.etree._BaseParser._parseUnicodeDoc (src\lxml\lxml.etree.c:96139)
>   File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:91290)
>   File "parser.pxi", line 683, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:92476)
>   File "parser.pxi", line 631, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:91904)
> XMLSyntaxError: line 14: Tag text invalid

**Second case:  blank text**
```
d = Article('http://www.siigroup.com/pressrelease.asp?ArticleID=237')
d.download()
d.parse()
d.text
d.title
```

> d = Article('http://www.siigroup.com/pressrelease.asp?ArticleID=237')
> d.download()
> d.parse()
> 
> d.text
> Out[21]: u''
> 
> d.title
> Out[22]: u'SI Group Announces Executive Leadership Changes'

Both URLs can be loaded in the browser, any idea why these happened? Thx.

**Comment by thundergolfer** [comment]
On your first case, I'm being told I can't `a.parse()` because I haven't yet done `a.download()`. I actually have done that it's just the the download is failing because of:

> requests.exceptions.SSLError: ("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",)

**Comment by thundergolfer** [comment]
In your second case, I think the point of failure is here in `article.py`.

> self.extractor.calculate_best_node(self.doc)

That line is returning `None` so the `.parse()` method doesn't even bother building the articles `text` up.
