### ISSUE TITLE
install error: During handling of the above exception, another exception occurred

### ISSUE THREAD

**Issue by seozed** [codelucas/newspaper#321]
OS: ubuntu 16.04 x64
python version: cpython 3.5.1
```
zed@zed-To-be-filled-by-O-E-M:~$ pip install newspaper

Collecting newspaper
  Downloading http://pypi.doubanio.com/packages/ad/f1/5dee1521042ffb8ece842a9608661fc756d366f2c2674afda45e70a6f5f9/newspaper-0.0.9.8.tar.gz (248kB)
    100% |████████████████████████████████| 256kB 6.1MB/s 
Collecting beautifulsoup4==4.3.2 (from newspaper)
  Downloading http://pypi.doubanio.com/packages/30/bd/5405ba01391d06646de9ec90cadeb3893fa355a06438966afff44531219a/beautifulsoup4-4.3.2.tar.gz (143kB)
    100% |████████████████████████████████| 143kB 6.0MB/s 
Collecting Pillow==2.5.1 (from newspaper)
  Downloading http://pypi.doubanio.com/packages/9f/95/0d9e63f043a77e298338c2e2c091084dbb370a5167dfdb4c67df45a19434/Pillow-2.5.1.zip (6.9MB)
    100% |████████████████████████████████| 6.9MB 7.1MB/s 
Collecting PyYAML==3.11 (from newspaper)
  Downloading http://pypi.doubanio.com/packages/04/60/abfb3a665ee0569b60c89148b7187ddd8a36cb65e254fba945ae1315645d/PyYAML-3.11.zip (371kB)
    100% |████████████████████████████████| 378kB 4.8MB/s 
Collecting cssselect==0.9.1 (from newspaper)
  Downloading http://pypi.doubanio.com/packages/aa/e5/9ee1460d485b94a6d55732eb7ad5b6c084caf73dd6f9cb0bb7d2a78fafe8/cssselect-0.9.1.tar.gz
Collecting lxml==3.3.5 (from newspaper)
  Downloading http://pypi.doubanio.com/packages/ae/a8/ad6c2350c65b357faf9a06c7428b5c6159b01bd3014eed93a75513843063/lxml-3.3.5.tar.gz (3.5MB)
    100% |████████████████████████████████| 3.5MB 2.9MB/s 
Collecting nltk==2.0.5 (from newspaper)
  Downloading http://pypi.doubanio.com/packages/50/9e/39418026bf8013bbc2852c7aec3fb21e4339f6cd694934496d67a19b53b8/nltk-2.0.5.tar.gz (954kB)
    100% |████████████████████████████████| 962kB 18.9MB/s 
    Complete output from command python setup.py egg_info:
    Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.21.tar.gz
    Extracting in /tmp/tmpmq9116q4
    Traceback (most recent call last):
      File "/tmp/pip-build-j7eik19m/nltk/distribute_setup.py", line 143, in use_setuptools
        raise ImportError
    ImportError
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-j7eik19m/nltk/setup.py", line 23, in <module>
        distribute_setup.use_setuptools()
      File "/tmp/pip-build-j7eik19m/nltk/distribute_setup.py", line 145, in use_setuptools
        return _do_download(version, download_base, to_dir, download_delay)
      File "/tmp/pip-build-j7eik19m/nltk/distribute_setup.py", line 125, in _do_download
        _build_egg(egg, tarball, to_dir)
      File "/tmp/pip-build-j7eik19m/nltk/distribute_setup.py", line 99, in _build_egg
        _extractall(tar)
      File "/tmp/pip-build-j7eik19m/nltk/distribute_setup.py", line 467, in _extractall
        self.chown(tarinfo, dirpath)
    TypeError: chown() missing 1 required positional argument: 'numeric_owner'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-j7eik19m/nltk/
```
Should be how to solve

**Comment by thundergolfer** [comment]
This looks to be related to your problem:

https://bugs.launchpad.net/lxml/+bug/1503807

**Comment by yprez** [comment]
The pypi package name for the Python3 version of newspaper `newspaper3k`.

Can you try: `pip install newspaper3k` instead?
