### ISSUE TITLE
Not able to install Newspaper on Python 2.7

### ISSUE THREAD

**Issue by nabanitade** [codelucas/newspaper#352]
All the requirements are complete but it fails saying something like this - 
 File "c:\temp\tmp4is8f3\distribute-0.6.21\pkg_resources.py", line 1745, in find_on_path
        path_item,entry,metadata,precedence=DEVELOP_DIST
      File "c:\temp\tmp4is8f3\distribute-0.6.21\pkg_resources.py", line 2121, in from_location
        py_version=py_version, platform=platform, **kw
      File "c:\temp\tmp4is8f3\distribute-0.6.21\pkg_resources.py", line 2100, in __init__
        self.project_name = safe_name(project_name or 'Unknown')
      File "c:\temp\tmp4is8f3\distribute-0.6.21\pkg_resources.py", line 1135, in safe_name
        return re.sub('[^A-Za-z0-9.]+', '-', name)
      File "C:\ProgramData\Anaconda2\lib\re.py", line 155, in sub
        return _compile(pattern, flags).sub(repl, string, count)
    RuntimeError: maximum recursion depth exceeded
    c:\users\nabanita\appdata\local\temp\pip-build-saxye8\nltk\distribute-0.6.21-py2.7.egg
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\nabanita\appdata\local\temp\pip-build-saxye8\nltk\setup.py", line 23, in <module>
        distribute_setup.use_setuptools()
      File "distribute_setup.py", line 145, in use_setuptools
        return _do_download(version, download_base, to_dir, download_delay)
      File "distribute_setup.py", line 125, in _do_download
        _build_egg(egg, tarball, to_dir)
      File "distribute_setup.py", line 116, in _build_egg
        raise IOError('Could not build the egg.')
    IOError: Could not build the egg.

**Comment by KillerCodeMonkey** [comment]
First big text in readme:

```Newspaper is a Python3 library!```

There is an extra branch for the buggy python 2 version:
https://github.com/codelucas/newspaper/tree/python-2-head

**Comment by codelucas** [comment]
please run `pip3 install newspaper3k` if you are on python3 OR `pip install newspaper` IF you are on python2
