### ISSUE TITLE
Missing files in recent pip installation

### ISSUE THREAD

**Issue by svrist** [codelucas/newspaper#361]
I'm having trouble running newspaper in python 2.7 in recent installs. My old installs of the same version still works. But in new virtualmachines and in new virtualenvs I get a newspaper installation which don't have any directories in it:

``` 
$ virtualenv /tmp/test1
New python executable in /tmp/test1/bin/python
Installing setuptools, pip, wheel...done.
$ . /tmp/test1/bin/activate 
(test1) $ pip --version
pip 9.0.1 from /tmp/test1/local/lib/python2.7/site-packages (python 2.7)
(test1) $ python --version
Python 2.7.6
(test1) $ pip install --no-cache-dir "newspaper>=0.0.9.8"   
Collecting newspaper>=0.0.9.8
/tmp/test1/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/tmp/test1/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading newspaper-0.0.9.8.tar.gz (248kB)
    100% |████████████████████████████████| 256kB 8.6MB/s 
Collecting beautifulsoup4==4.3.2 (from newspaper>=0.0.9.8)
....
Installing collected packages: beautifulsoup4, Pillow, PyYAML, cssselect, lxml, nltk, requests, six, jieba, feedparser, tldextract, feedfinder2, python-dateutil, newspaper
  Running setup.py install for beautifulsoup4 ... done
  Running setup.py install for Pillow ... done
  Running setup.py install for PyYAML ... done
  Running setup.py install for cssselect ... done
  Running setup.py install for lxml ... -^[OF^[OF^[Odone
  Running setup.py install for nltk ... done
  Found existing installation: six 1.10.0
    Uninstalling six-1.10.0:
      Successfully uninstalled six-1.10.0
  Running setup.py install for jieba ... done
  Running setup.py install for feedparser ... done
  Running setup.py install for tldextract ... done
  Running setup.py install for feedfinder2 ... done
  Running setup.py install for newspaper ... done
Successfully installed Pillow-2.5.1 PyYAML-3.11 beautifulsoup4-4.3.2 cssselect-0.9.1 feedfinder2-0.0.1 feedparser-5.1.3 jieba-0.35 lxml-3.3.5 newspaper-0.0.9.8 nltk-2.0.5 python-dateutil-2.4.0 requests-2.3.0 six-1.7.3 tldextract-1.5.1
(test1) $ python
Python 2.7.6 (default, Oct 26 2016, 20:30:19) 
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import newspaper
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/test1/local/lib/python2.7/site-packages/newspaper/__init__.py", line 10, in <module>
    from .article import Article, ArticleException
  File "/tmp/test1/local/lib/python2.7/site-packages/newspaper/article.py", line 14, in <module>
    from . import nlp
  File "/tmp/test1/local/lib/python2.7/site-packages/newspaper/nlp.py", line 17, in <module>
    with open(settings.NLP_STOPWORDS_EN, 'r') as f:
IOError: [Errno 2] No such file or directory: '/tmp/test1/local/lib/python2.7/site-packages/newspaper/resources/misc/stopwords-nlp-en.txt'
>>>
(test1) $ ls -1tr /tmp/test1/local/lib/python2.7/site-packages/newspaper/
cleaners.py
nlp.py
configuration.py
__init__.py
utils.py
urls.py
text.py
source.py
settings.py
parsers.py
outputformatters.py
network.py
mthreading.py
images.py
extractors.py
article.py
api.py
version.py
outputformatters.pyc
text.pyc
nlp.pyc
__init__.pyc
cleaners.pyc
api.pyc
version.pyc
extractors.pyc
urls.pyc
source.pyc
images.pyc
configuration.pyc
parsers.pyc
network.pyc
mthreading.pyc
article.pyc
utils.pyc
settings.pyc
(test1) $ 
```

**Comment by svrist** [comment]
When it works on my old installs it's because it got a cached wheel which it uses as install. When I disable the cache or install from a fresh VM + Virtualenv it'll install via an egg

**Comment by svrist** [comment]
Reproduced on a python:2 gitlab ci docker image last night.
```
../venvs/api/lib/python2.7/site-packages/newspaper/nlp.py:17: in <module>
    with open(settings.NLP_STOPWORDS_EN, 'r') as f:
E   IOError: [Errno 2] No such file or directory: '/builds/publia/publia/python/venvs/api/lib/python2.7/site-packages/newspaper/resources/misc/stopwords-nlp-en.txt'
``` 
I then, noon (CEST) today, pressed retry and the issue was gone

**Comment by hailuns** [comment]
I'm getting the same issue both yesterday and today.

**Comment by codelucas** [comment]
This is so weird, I can't reproduce :\

@svrist do you have any hints why your latest retry worked .. despite all older retries failing? What in your coding environment could have changed?

**Comment by codelucas** [comment]
OK - just reproduced this on python2. Works on python3. This is so weird. Let me try to fix it and push a new deployment in pip. Something must have broke the deployment my last push 2 days ago

@hailuns @svrist

**Comment by codelucas** [comment]
Good news! Problem has been found, I just pushed a new newspaper (python2) package to pip, please update now: `pip install newspaper==0.1.0.2`

The root cause was that 2 days ago i accidentally pushed a python2 newspaper binary without being in virutalenv (causing my setuptools import to be much much much older) which mis-interpreted MANIFEST.in causing all of the data files to be lost!

**Comment by codelucas** [comment]
It works for me!

```
Successfully installed newspaper-0.1.0.2
(python2-newspaper-test) ------------------------------------------------------------
~VIRTUAL_ENV » python                                                                                                                                       l@mbp
Python 2.7.10 (default, Feb  7 2017, 00:08:15)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import newspaper

```
