### ISSUE TITLE
installation problem...

### ISSUE THREAD

**Issue by martianmartian** [codelucas/newspaper#365]
`pip3 install newspaper
Collecting newspaper
  Downloading newspaper-0.0.9.8.tar.gz (248kB)
    100% |████████████████████████████████| 256kB 272kB/s 
Collecting beautifulsoup4==4.3.2 (from newspaper)
  Downloading beautifulsoup4-4.3.2.tar.gz (143kB)
    100% |████████████████████████████████| 143kB 355kB/s 
Collecting Pillow==2.5.1 (from newspaper)
  Downloading Pillow-2.5.1.zip (6.9MB)
    100% |████████████████████████████████| 6.9MB 93kB/s 
Collecting PyYAML==3.11 (from newspaper)
  Downloading PyYAML-3.11.zip (371kB)
    100% |████████████████████████████████| 378kB 183kB/s 
Collecting cssselect==0.9.1 (from newspaper)
  Downloading cssselect-0.9.1.tar.gz
Collecting lxml==3.3.5 (from newspaper)
  Downloading lxml-3.3.5.tar.gz (3.5MB)
    100% |████████████████████████████████| 3.5MB 306kB/s 
Collecting nltk==2.0.5 (from newspaper)
  Downloading nltk-2.0.5.tar.gz (954kB)
    100% |████████████████████████████████| 962kB 848kB/s 
    Complete output from command python setup.py egg_info:
    Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.21.tar.gz
    Extracting in /var/folders/6h/hvh131sn68z2hxtk6y8jszd40000gn/T/tmpptqe5gls
    Traceback (most recent call last):
      File "/private/var/folders/6h/hvh131sn68z2hxtk6y8jszd40000gn/T/pip-build-c4a_m3bm/nltk/distribute_setup.py", line 143, in use_setuptools
        raise ImportError
    ImportError
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/6h/hvh131sn68z2hxtk6y8jszd40000gn/T/pip-build-c4a_m3bm/nltk/setup.py", line 23, in <module>
        distribute_setup.use_setuptools()
      File "/private/var/folders/6h/hvh131sn68z2hxtk6y8jszd40000gn/T/pip-build-c4a_m3bm/nltk/distribute_setup.py", line 145, in use_setuptools
        return _do_download(version, download_base, to_dir, download_delay)
      File "/private/var/folders/6h/hvh131sn68z2hxtk6y8jszd40000gn/T/pip-build-c4a_m3bm/nltk/distribute_setup.py", line 125, in _do_download
        _build_egg(egg, tarball, to_dir)
      File "/private/var/folders/6h/hvh131sn68z2hxtk6y8jszd40000gn/T/pip-build-c4a_m3bm/nltk/distribute_setup.py", line 99, in _build_egg
        _extractall(tar)
      File "/private/var/folders/6h/hvh131sn68z2hxtk6y8jszd40000gn/T/pip-build-c4a_m3bm/nltk/distribute_setup.py", line 467, in _extractall
        self.chown(tarinfo, dirpath)
    TypeError: chown() missing 1 required positional argument: 'numeric_owner'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/6h/hvh131sn68z2hxtk6y8jszd40000gn/T/pip-build-c4a_m3bm/nltk/`

**Comment by yprez** [comment]
@martianmartian if you're installing on Python3 the correct package name is `newspaper3k`.
