### ISSUE TITLE
get text error on this site

### ISSUE THREAD

**Issue by liufengsoft** [codelucas/newspaper#407]
url:
http://tech.sina.com.cn/i/2017-07-28/doc-ifyinvwu2861744.shtml

code:
```
import requests
from newspaper import fulltext


url = "http://tech.sina.com.cn/i/2017-07-28/doc-ifyinvwu2861744.shtml"

html = requests.get(url).text
text = fulltext(html)
print(text)
```
error:
```
Traceback (most recent call last):
  File "/Users/eric/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-P/ch-0/171.4694.67/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1591, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Users/eric/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-P/ch-0/171.4694.67/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1018, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Users/eric/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-P/ch-0/171.4694.67/PyCharm.app/Contents/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/eric/dev/HtmlExtractor/src/main.py", line 14, in <module>
    text = fulltext(html)
  File "/usr/local/lib/python3.6/site-packages/newspaper/api.py", line 91, in fulltext
    top_node = extractor.post_cleanup(top_node)
  File "/usr/local/lib/python3.6/site-packages/newspaper/extractors.py", line 1043, in post_cleanup
    node = self.add_siblings(top_node)
  File "/usr/local/lib/python3.6/site-packages/newspaper/extractors.py", line 872, in add_siblings
    baseline_score_siblings_para = self.get_siblings_score(top_node)
  File "/usr/local/lib/python3.6/site-packages/newspaper/extractors.py", line 929, in get_siblings_score
    nodes_to_check = self.parser.getElementsByTag(top_node, tag='p')
  File "/usr/local/lib/python3.6/site-packages/newspaper/parsers.py", line 117, in getElementsByTag
    elems = node.xpath(selector, namespaces={"re": NS})
AttributeError: 'NoneType' object has no attribute 'xpath'
```

**Comment by rockie-yang** [comment]
It works with following code. Not use the `fulltext` function though

    from newspaper import Article

    article = Article('http://tech.sina.com.cn/i/2017-07-28/doc-ifyinvwu2861744.shtml', language='zh')

    article.download()
    article.parse()
    print(article.text)
