### ISSUE TITLE
newspaper.build(...) error

### ISSUE THREAD

**Issue by GitHubSuperHero** [codelucas/newspaper#447]
Hi,
I'm new to python and I don't know how to fix this.

```
Traceback (most recent call last):
TypeError: get_request_kwargs() missing 1 required positional argument: 'headers'
  File "/usr/local/lib/python3.5/dist-packages/newspaper3k-0.2.2-py3.5.egg/newspaper/mthreading.py", line 38, in run
    func(*args, **kargs)
  File "/usr/local/lib/python3.5/dist-packages/newspaper3k-0.2.2-py3.5.egg/newspaper/network.py", line 105, in send
    self.resp = requests.get(self.url, **get_request_kwargs(self.timeout, self.useragent, self.proxies))
TypeError: get_request_kwargs() missing 1 required positional argument: 'headers'
```

Can someone help me please?

**Comment by codelucas** [comment]
Hey @GitHubSuperHero, this was a bug that happened last night for one hour - i have since pushed a fix.

can you please uninstall and reinstall newspaper3k? 

```
pip uninstall newspaper3k
pip install newspaper3k
```

**Comment by codelucas** [comment]
If you are using master, please pull the latest commits with
```
git pull
```

**Comment by GitHubSuperHero** [comment]
I solved the problem using

`pip3 install git+https://github.com/codelucas/newspaper.git`

Thanks codelucas
