### ISSUE TITLE
Can not install with Python 2.7.12

### ISSUE THREAD

**Issue by caiyajing9210** [codelucas/newspaper#471]
when I run `pip install newspaper ` under Ubuntu 16.04 with python 2.7.12, I see this 
```
yajing@yajing:~$ sudo -H pip install newspaper
Requirement already satisfied: newspaper in /usr/local/lib/python2.7/dist-packages/newspaper-0.1.0.7-py2.7.egg
Collecting beautifulsoup4==4.3.2 (from newspaper)
  Using cached beautifulsoup4-4.3.2.tar.gz
Collecting Pillow==2.5.1 (from newspaper)
  Using cached Pillow-2.5.1.zip
Collecting PyYAML==3.11 (from newspaper)
  Using cached PyYAML-3.11.zip
Collecting cssselect==0.9.1 (from newspaper)
  Using cached cssselect-0.9.1.tar.gz
Collecting lxml==3.3.5 (from newspaper)
  Using cached lxml-3.3.5.tar.gz
Collecting nltk==2.0.5 (from newspaper)
  Using cached nltk-2.0.5.tar.gz
    Complete output from command python setup.py egg_info:
    Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.21.tar.gz
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-auxeV6/nltk/setup.py", line 23, in <module>
        distribute_setup.use_setuptools()
      File "distribute_setup.py", line 145, in use_setuptools
        return _do_download(version, download_base, to_dir, download_delay)
      File "distribute_setup.py", line 124, in _do_download
        to_dir, download_delay)
      File "distribute_setup.py", line 193, in download_setuptools
        src = urlopen(url)
      File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
        return opener.open(url, data, timeout)
      File "/usr/lib/python2.7/urllib2.py", line 435, in open
        response = meth(req, response)
      File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
        'http', request, response, code, msg, hdrs)
      File "/usr/lib/python2.7/urllib2.py", line 473, in error
        return self._call_chain(*args)
      File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
        result = func(*args)
      File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
        raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
    urllib2.HTTPError: HTTP Error 403: SSL is required
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-auxeV6/nltk/

```
Can anyone tell me how fix this problem

**Comment by caiyajing9210** [comment]
by the way, I can install the version of 0.0.8.

**Comment by janismdhanbad** [comment]
Getting the same problem.

**Comment by caiyajing9210** [comment]
@janismdhanbad Do you find the solution to solve this problem?

**Comment by adi-sharma** [comment]
I'm getting the same error

**Comment by janismdhanbad** [comment]
@caiyajing9210 @adi-sharma , I was not able to install it on python 2.7 but on python 3.5.

pip install newspaper3k

That worked for me.

**Comment by gliptak** [comment]
A possible workaround is at https://stackoverflow.com/questions/46967488/getting-error-403-while-installing-package-with-pip/46979531#46979531

**Comment by codelucas** [comment]
Hey guys! I just pushed two PRs, 

- One to fix this problem by updating requirements.txt in the python-2 branch: https://github.com/codelucas/newspaper/pull/493
- Another to add CI integration tests to the python-2 branch, they are succeeding so not 100% of people are getting this error and I personally could not reproduce it.

**Comment by codelucas** [comment]
Please close this after you confirm the install is working on the python-2-head branch, I have not pushed it to the master pip repository yet

**Comment by trimbilrepo** [comment]
@codelucas the problem was the NLTK version. version 2.0.5 is the old version and hosted in http rather than https.
you can remove nltk and tried install newspaper to reproduce the problem.

to solve this issue: just donwload newspaper from pip website
`wget https://pypi.python.org/packages/d8/07/5765cc9c36e2be1a0f0e615b7a092129e1ba30a25182506dea437290c193/newspaper-0.1.0.7.tar.gz`

then extract
`tar -xzf newspaper-0.1.0.7.tar.gz`

edit the requirement.txt with new requirement.txt in repository

```
tar -czvf  newspaper-0.1.0.7.tar.gz newspaper-0.1.0.7
pip install newspaper-0.1.0.7.tar.gz
```
you should be fine

**Comment by Florian-Roessler** [comment]
@codelucas 
I can confirm that installing newspaper in a Python 2.7.14 conda env works via 

`pip install git+https://github.com/codelucas/newspaper.git@python-2-head` 

which contains the new requirements.txt file.

**Comment by codelucas** [comment]
@trimbilrepo @Florian-Roessler thanks for resolving this guys.

This must mean the pypi package doesn't have the updated requirements.txt..
🤦‍♂️ I'll push a new version today
