### ISSUE TITLE
problems installing in Anaconda3-5.0.1-Windows-x86_64

### ISSUE THREAD

**Issue by theiman112860** [codelucas/newspaper#502]
Hi,

I tried to install newspaper using the following:

        conda install -c conda-forge newspaper3k

Everything seemed to go fine.  When I tried to run the following:

import newspaper
cnn_paper = newspaper.build('http://cnn.com')

        for article in cnn_paper.articles:
            print(article.url)

I get the following:

runfile('C:/Users/theiman/.spyder-py3/temp.py', wdir='C:/pythoncode')
Traceback (most recent call last):

  File "<ipython-input-2-4a3b601f4117>", line 1, in <module>
    runfile('C:/Users/theiman/.spyder-py3/temp.py', wdir='C:/pythoncode')

  File "C:\Users\theiman\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 710, in runfile
    execfile(filename, namespace)

  File "C:\Users\theiman\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 101, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/theiman/.spyder-py3/temp.py", line 7, in <module>
    import newspaper

  File "C:\Users\theiman\AppData\Local\Continuum\anaconda3\lib\site-packages\newspaper\__init__.py", line 10, in <module>
    from .api import (build, build_article, fulltext, hot, languages,

  File "C:\Users\theiman\AppData\Local\Continuum\anaconda3\lib\site-packages\newspaper\api.py", line 14, in <module>
    from .article import Article

  File "C:\Users\theiman\AppData\Local\Continuum\anaconda3\lib\site-packages\newspaper\article.py", line 14, in <module>
    from . import images

  File "C:\Users\theiman\AppData\Local\Continuum\anaconda3\lib\site-packages\newspaper\images.py", line 18, in <module>
    from PIL import Image, ImageFile

  File "C:\Users\theiman\AppData\Local\Continuum\anaconda3\lib\site-packages\PIL\Image.py", line 56, in <module>
    from . import _imaging as core

ImportError: DLL load failed: The specified module could not be found.

Any ideas on what could be going wrong?

Sincerely,

tom

**Comment by ColCarroll** [comment]
It looks like that is actually a problem with `pillow`:  installing newspaper should have also installed `pillow>=3.3.0`.  Can you check your version with `pip freeze | grep Pillow`, and confirm this is actually the problem in a python shell with `from PIL import *`?

**Comment by theiman112860** [comment]
Hi ColCarroll! Thank you for looking at my issue!!  I did check and I got Pillow==5.0.0.. Any ideas on what is going wrong?  Thank you again!!

**Comment by ColCarroll** [comment]
Looks like it is an ongoing problem, but the current solution is to `conda uninstall pillow` and then `pip install pillow`, though maybe the new feedstock is already on conda: https://github.com/python-pillow/Pillow/issues/2945

**Comment by theiman112860** [comment]
I just tried that and I still can't use newspaper..
