### ISSUE TITLE
fulltext(html) error

### ISSUE THREAD

**Issue by pua4pai** [codelucas/newspaper#533]
hi ,
like this:
```
>>> fulltext(html)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/newspaper/api.py", line 91, in fulltext
    top_node = extractor.post_cleanup(top_node)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/newspaper/extractors.py", line 1040, in post_cleanup
    node = self.add_siblings(top_node)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/newspaper/extractors.py", line 869, in add_siblings
    baseline_score_siblings_para = self.get_siblings_score(top_node)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/newspaper/extractors.py", line 926, in get_siblings_score
    nodes_to_check = self.parser.getElementsByTag(top_node, tag='p')
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/newspaper/parsers.py", line 123, in getElementsByTag
    elems = node.xpath(selector, namespaces=NS)
AttributeError: 'NoneType' object has no attribute 'xpath'
```

this html local html , why?

**Comment by MohamedHuzien** [comment]
use the second parameter `language`, and specify the language because the default lang is `en` 
```python
def fulltext(html, language='en'):
...
```
i thinks this html content another language

**Comment by codelucas** [comment]
@pua4pai can you please be specific of what the HTML is or which URL you are parsing? Without that information we can't help you debug

**Comment by pua4pai** [comment]
@MohamedHuzien yes,the 'zh'

**Comment by gugu** [comment]
For example this:

https://www.bd.nl/vught/nieuwe-en-grotere-entree-voor-gevangenis-vught-aan-de-zijde-van-woonoord-lunetten~afa1a174/

**Comment by shashank7596** [comment]
Hello,

   I had similar issue while scraping url : http://feeds.bizjournals.com/~r/industry_6/~3/IB81lC9ZgXc/waltham-biotechs-drug-bests-alexions-blockbuster.html

url = 'http://feeds.bizjournals.com/~r/industry_6/~3/IB81lC9ZgXc/waltham-biotechs-drug-bests-alexions-blockbuster.html'
html = scraper.get(url)
article_text = fulltext(html.text,language = 'en')
print(article_text)

This gives me error:
ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

Traceback (most recent call last):
AttributeError: 'NoneType' object has no attribute 'xpath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
AttributeError: 'AttributeError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
AssertionError
---------------------------------------------------------------------------


when I tried to catch exception and print it gives me : **'NoneType' object has no attribute 'xpath'**

Can anyone help. Thanks in advance.
