### ISSUE TITLE
ValueError: All strings must be XML compatible: Unicode or ASCII, no NULL bytes or control characters

### ISSUE THREAD

**Issue by monajalal** [codelucas/newspaper#541]
So I have about 10000 URLs I have to go through and after a long time of run, I got this error.

Any rough idea how could I avoid similar problems?

```
current URL is:  http://www.gbtribune.com/section/28/article/110312/
Traceback (most recent call last):
  File "/scratch2/news_bias/image_retrieval.py", line 30, in <module>
    article.parse()
  File "/scratch/sjn/anaconda/lib/python3.6/site-packages/newspaper/article.py", line 240, in parse
    self.doc = document_cleaner.clean(self.doc)
  File "/scratch/sjn/anaconda/lib/python3.6/site-packages/newspaper/cleaners.py", line 69, in clean
    doc_to_clean = self.div_to_para(doc_to_clean, 'div')
  File "/scratch/sjn/anaconda/lib/python3.6/site-packages/newspaper/cleaners.py", line 239, in div_to_para
    div.set(name, value)
  File "/scratch/sjn/anaconda/lib/python3.6/site-packages/lxml/html/__init__.py", line 249, in set
    super(HtmlElement, self).set(key, value)
  File "src/lxml/etree.pyx", line 826, in lxml.etree._Element.set (src/lxml/etree.c:52983)
  File "src/lxml/apihelpers.pxi", line 575, in lxml.etree._setAttributeValue (src/lxml/etree.c:24320)
  File "src/lxml/apihelpers.pxi", line 1444, in lxml.etree._utf8 (src/lxml/etree.c:32943)
ValueError: All strings must be XML compatible: Unicode or ASCII, no NULL bytes or control characters

Process finished with exit code 1
```

```
    try:
        URL = row['URL']
        article = Article(URL)
        article.download()
        # print(article.html)
        #while article.download_state == 0:  # ArticleDownloadState.NOT_STARTED is 0
        #    time.sleep(1)
        article.parse()
        #print(article.authors)
        #print(article.publish_date)
        # print(article.text)
        top_image = article.top_image
        if top_image:
            img_list.append(top_image)
        else:
            img_list.append('NA')
        print(article.movies)
        article.nlp()
        #print(article.keywords)
        #print(article.summary)
    except newspaper.article.ArticleException:
        continue
        img_list.append('NA')
```

**Comment by monajalal** [comment]
definitely not a good idea but here is what I did:
```
try:
    #URL = row['URL']
    URL = "http://www.gbtribune.com/section/28/article/110312/"
    article = Article(URL)
    article.download()
    # print(article.html)
    # while article.download_state == 0:  # ArticleDownloadState.NOT_STARTED is 0
    #    time.sleep(1)
    article.parse()
    # print(article.authors)
    # print(article.publish_date)
    # print(article.text)
    top_image = article.top_image
    if top_image:
        img_list.append(top_image)
    else:
        img_list.append('NA')
    print(article.movies)
    article.nlp()
    # print(article.keywords)
    # print(article.summary)
except (newspaper.article.ArticleException, ValueError) as e:
    img_list.append('NA')
    #continue
    pass
```
