### ISSUE TITLE
Error when using newspaper3k with flask on CentOS

### ISSUE THREAD

**Issue by oliwang** [codelucas/newspaper#690]
I'm using python3.6, gunicorn and nginx to host a flask site on CentOS.

I created a python file called ContentExtractor.py with a class called ContentExtractor which uses newspaper3k.
```
class ContentExtractor(object):
    def __init__(self, page_url):
        self.page_url = page_url
        self.article = Article(self.page_url)
        self.article.download()
        self.article.parse()

    def getTitle(self):
        return self.article.title

    def getContent(self):
        return self.article.text
```

My flask file website.py then calls this class but an error appears,
```
[2019-03-16 01:32:53,261] ERROR in app: Exception on /api/webpage_reader/ [GET]
Traceback (most recent call last):
  File "/home/website/anaconda3/envs/python3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/website/anaconda3/envs/python3/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/website/anaconda3/envs/python3/lib/python3.6/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/website/anaconda3/envs/python3/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/website/anaconda3/envs/python3/lib/python3.6/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/website/Website/website.py", line 36, in get
    return api_webpage_reader(page_url)
  File "/home/website/Website/website.py", line 65, in api_webpage_reader
    CE_obj = CE_class(page_url)
  File "/home/website/Website/ContentExtractor.py", line 16, in __init__
    def getTitle(self):
  File "/home/website/anaconda3/envs/python3/lib/python3.6/site-packages/newspaper/article.py", line 191, in parse
    self.throw_if_not_downloaded_verbose()
  File "/home/website/anaconda3/envs/python3/lib/python3.6/site-packages/newspaper/article.py", line 532, in throw_if_not_downloaded_verbose
    (self.download_exception_msg, self.url))
newspaper.article.ArticleException: Article `download()` failed with HTTPSConnectionPool(host='www.voanews.com', port=443): Max retries exceeded with url: /a/china-saudi-arabia-try-to-walk-together-amid-hurdles/4797858.html (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7ff0c7a52748>, 'Connection to www.voanews.com timed out. (connect timeout=7)')) on URL https://www.voanews.com/a/china-saudi-arabia-try-to-walk-together-amid-hurdles/4797858.html
```

I tried running the ContentExtractor.py file separately and it works just fine with the same url.

**Comment by oliwang** [comment]
I tested this on more urls, I think this could be because my server is in China...

**Comment by codelucas** [comment]
This is an interesting use case and worth flagging in the README for our other chinese users. Thanks for flagging though
