### ISSUE TITLE
Fulltext test from readme fails 1 test

### ISSUE THREAD

**Issue by irinaid** [codelucas/newspaper#816]
Output when running 
$ sudo python3 tests/unit_tests.py fulltext

[...]
FAIL: test_exhaustive (__main__.ExhaustiveFullTextCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/unit_tests.py", line 42, in run
    method(*args, **kw)
  File "tests/unit_tests.py", line 143, in test_exhaustive
    self.assertGreaterEqual(20, total_fulltext_failed)
AssertionError: 20 not greater than or equal to 29

----------------------------------------------------------------------
Ran 45 tests in 18.955s

FAILED (failures=1, skipped=4)

**Comment by Bachstelze** [comment]
Could the ad blocker wall be a problem?
In the end every site is unique and can have its own reason for failure.
We probably duplicate https://github.com/codelucas/newspaper/issues/631
