### ISSUE TITLE
re.error: bad escape \p at position 2

### ISSUE THREAD

**Issue by fabioluciano** [codelucas/newspaper#822]
When ii tried to import the library i receive the follow error:

```python
python3
Python 3.8.2 (default, Apr 27 2020, 15:53:34)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from newspaper import Article
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/fabioluciano/.local/lib/python3.8/site-packages/newspaper/__init__.py", line 10, in <module>
    from .article import Article, ArticleException
  File "/home/fabioluciano/.local/lib/python3.8/site-packages/newspaper/article.py", line 13, in <module>
    from . import network
  File "/home/fabioluciano/.local/lib/python3.8/site-packages/newspaper/network.py", line 14, in <module>
    from .configuration import Configuration
  File "/home/fabioluciano/.local/lib/python3.8/site-packages/newspaper/configuration.py", line 15, in <module>
    from .parsers import Parser
  File "/home/fabioluciano/.local/lib/python3.8/site-packages/newspaper/parsers.py", line 19, in <module>
    from . import text
  File "/home/fabioluciano/.local/lib/python3.8/site-packages/newspaper/text.py", line 59, in <module>
    class StopWords(object):
  File "/home/fabioluciano/.local/lib/python3.8/site-packages/newspaper/text.py", line 61, in StopWords
    PUNCTUATION = re.compile(
  File "/usr/lib/python3.8/re.py", line 250, in compile
    return _compile(pattern, flags)
  File "/usr/lib/python3.8/re.py", line 302, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python3.8/sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib/python3.8/sre_parse.py", line 948, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
  File "/usr/lib/python3.8/sre_parse.py", line 443, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "/usr/lib/python3.8/sre_parse.py", line 554, in _parse
    code1 = _class_escape(source, this)
  File "/usr/lib/python3.8/sre_parse.py", line 349, in _class_escape
    raise source.error('bad escape %s' % escape, len(escape))
re.error: bad escape \p at position 2
```

**Comment by AndreaRe9** [comment]
Have you installed the correct version of newspaper? If you are using python 3 you have to install newspaper3k not newspaper. So: `pip3 install newspaper3k` instead of `pip3 install newspaper`.
