### ISSUE TITLE
Undocumented dependency

### ISSUE THREAD

**Issue by krikru** [codelucas/newspaper#845]
Hi,

I got a crash with the following traceback:

```python
Traceback (most recent call last):
...
  File "D:\ProgramData\Miniconda3\envs\scraper\lib\site-packages\newspaper\article.py", line 248, in parse
    self.top_node = self.extractor.calculate_best_node(self.doc)
  File "D:\ProgramData\Miniconda3\envs\scraper\lib\site-packages\newspaper\extractors.py", line 778, in calculate_best_node
    get_stopword_count(text_node)
  File "D:\ProgramData\Miniconda3\envs\scraper\lib\site-packages\newspaper\text.py", line 90, in get_stopword_count
    candidate_words = self.candidate_words(stripped_input.lower())
  File "D:\ProgramData\Miniconda3\envs\scraper\lib\site-packages\newspaper\text.py", line 194, in candidate_words
    import tinysegmenter
ModuleNotFoundError: No module named 'tinysegmenter'
```

Is the dependency on `tinysegmenter` documented anywhere? Otherwise, it should probably be mentioned. Then, is this the only dependency that is undocumented, or are there more?

**Comment by Anacoder1** [comment]
tinysegmenter (v0.3) is listed as a dependency [here](https://github.com/codelucas/newspaper/blob/master/requirements.txt), though.
